import { createFileRoute } from "@tanstack/react-router";
import { Mail, MapPin, Phone } from "lucide-react";
import { ContactForm } from "@/components/forms";
import { PageHero, SectionHeading } from "@/components/site-components";
import { contact } from "@/lib/site-data";
import { pageHead } from "@/lib/seo";
import image from "@/assets/tekma-property.jpg";

export const Route=createFileRoute("/contact")({head:()=>pageHead("Contact TEKMA Global Partners Abuja","Contact TEKMA Global Partners in Abuja for energy brokerage, vessel, asset, property and consultancy enquiries.","/contact"),component:Contact});
function Contact(){return <><PageHero eyebrow="Contact TEKMA" title="Start a conversation." copy="Speak with our team about a credible opportunity, a specific requirement or a potential introduction." image={image}/><section><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.7fr_1.3fr] lg:px-8 lg:py-28"><div><SectionHeading eyebrow="Abuja, Nigeria" title="TEKMA Global Partners Limited"/><address className="mt-8 not-italic leading-8 text-muted-foreground">{contact.address}</address><div className="mt-8 grid gap-3"><a href={`tel:${contact.phone.replace(/\s/g,"")}`} className="flex min-h-12 items-center gap-3 font-semibold text-navy"><Phone className="size-5 text-energy"/>Call us: {contact.phone}</a><a href={`mailto:${contact.email}`} className="flex min-h-12 items-center gap-3 break-all font-semibold text-navy"><Mail className="size-5 text-magenta"/>Email us: {contact.email}</a><a href="https://www.google.com/maps/search/?api=1&query=B10%20AMAC%20Complex%20Kabale%20Close%20Zone%203%20Wuse%20Abuja" target="_blank" rel="noreferrer" className="flex min-h-12 items-center gap-3 font-semibold text-navy"><MapPin className="size-5 text-gold"/>Get directions</a></div></div><ContactForm/></div></section><section className="bg-surface"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid min-h-80 place-items-center border border-border bg-background text-center"><div><MapPin className="mx-auto size-9 text-petroleum"/><h2 className="mt-4 text-2xl font-bold text-navy">Wuse District, Abuja</h2><p className="mt-2 text-muted-foreground">Use the directions link for live map navigation.</p></div></div></div></section></>}