import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CTASection, GlobalMap, SectionHeading } from "@/components/site-components";
import { services } from "@/lib/site-data";
import hero from "@/assets/tekma-energy-hero.jpg";
import advisory from "@/assets/tekma-advisory.jpg";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"TEKMA Global Partners | Energy & Asset Brokerage"},{name:"description",content:"Global oil and gas, energy asset, vessel and commercial real estate brokerage and consultancy from Abuja, Nigeria."},{property:"og:title",content:"TEKMA Global Partners | Energy & Asset Brokerage"},{property:"og:description",content:"Connecting qualified buyers, sellers, asset owners, investors and mandates across global markets."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"ProfessionalService",name:"TEKMA Global Partners Limited",address:{"@type":"PostalAddress",streetAddress:"B10 AMAC Complex, Kabale Close, Zone 3, Wuse District",addressLocality:"Abuja",addressCountry:"NG"},telephone:"+234 809 549 5128",email:"info@tekmaglobalpartners.com.ng"})}]}),component:Home});

function Home(){return <>
 <section className="relative min-h-[calc(100dvh-5rem)] overflow-hidden bg-navy text-primary-foreground"><img src={hero} alt="Offshore energy infrastructure at sea" width={1920} height={1088} fetchPriority="high" className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/80 to-navy/15"/><div className="relative mx-auto flex min-h-[calc(100dvh-5rem)] max-w-7xl items-center px-5 py-20 lg:px-8"><div className="max-w-4xl"><p className="mb-6 text-xs font-bold uppercase tracking-[0.22em] text-gold">Energy · Assets · Marine · Property · Consultancy</p><h1 className="text-4xl font-extrabold uppercase leading-[1.04] sm:text-6xl lg:text-7xl">Global connections.<br/>Strategic opportunities.<br/><span className="text-gold">Trusted partnerships.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-primary-foreground/80 sm:text-lg">Connecting qualified buyers, sellers, asset owners, investors and mandates across energy, maritime and commercial real estate markets.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="min-h-12 rounded-none bg-gold text-navy hover:bg-primary-foreground"><Link to="/oil-and-gas">Explore our services <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline" className="min-h-12 rounded-none border-primary-foreground/40 bg-transparent text-primary-foreground hover:bg-primary-foreground hover:text-navy"><Link to="/opportunities">Discuss an opportunity</Link></Button></div></div></div><ArrowDown className="absolute bottom-7 right-8 size-5 text-primary-foreground/60 gentle-drift" aria-hidden="true"/></section>
 <section><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-28"><SectionHeading eyebrow="Who we are" title="Connecting opportunities across global markets"/><div><p className="text-lg leading-8 text-foreground">TEKMA Global Partners Limited is an experienced brokerage and consultancy firm with an extensive network of partners and business relationships across international markets.</p><p className="mt-5 leading-8 text-muted-foreground">We facilitate opportunities across oil and gas, energy assets and acreages, marine vessels, land and commercial real estate. Our approach combines market access, professional execution, discretion and a commitment to creating sustainable value for all parties.</p><Link to="/about" className="mt-7 inline-flex items-center gap-2 font-bold text-petroleum">Learn more about TEKMA <ArrowRight className="size-4"/></Link></div></div></section>
 <section className="bg-navy text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-28"><SectionHeading eyebrow="Global reach" title="Global access. Local understanding." copy="Through our network of partners, buyers, sellers, asset owners and authorised mandates, TEKMA facilitates opportunities across international markets." light/><GlobalMap/></div></section>
 <section><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionHeading eyebrow="Our expertise" title="Integrated brokerage and advisory capabilities"/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(s=><Link to={s.href} key={s.href} className={`group min-h-64 border border-border border-t-4 ${s.accent} bg-background p-7 transition-all hover:-translate-y-1 hover:shadow-xl`}><p className="text-xs font-bold text-muted-foreground">{s.number}</p><h3 className="mt-12 text-2xl font-bold text-navy">{s.title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{s.description}</p><ArrowRight className="mt-5 size-5 text-petroleum transition-transform group-hover:translate-x-1"/></Link>)}<Link to="/opportunities" className="group min-h-64 border border-border border-t-4 border-ocean bg-surface p-7 transition-all hover:-translate-y-1 hover:shadow-xl"><p className="text-xs font-bold text-muted-foreground">06</p><h3 className="mt-12 text-2xl font-bold text-navy">Global Introductions</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Connecting qualified principals and authorised mandates while seeking to reduce unnecessary intermediary chains.</p></Link></div></div></section>
 <section className="bg-surface"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionHeading eyebrow="How we work" title="From opportunity to connection"/><ol className="mt-12 grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-5">{["Understand the Requirement","Identify Qualified Parties","Establish Direct Connections","Facilitate Engagement","Support Transaction Progress"].map((x,i)=><li key={x} className="bg-background p-6"><span className="text-xs font-bold text-petroleum">0{i+1}</span><p className="mt-6 font-bold text-navy">{x}</p></li>)}</ol></div></section>
 <section className="overflow-hidden bg-background"><div className="mx-auto grid max-w-7xl items-stretch lg:grid-cols-2"><div className="px-5 py-20 lg:px-8"><SectionHeading eyebrow="Direct connection philosophy" title="Reducing complexity. Connecting the right parties." copy="Where possible, TEKMA works with direct buyers, sellers and duly authorised mandate holders. This helps reduce unnecessary intermediary chains, improve communication and support more efficient transaction processes."/><div className="mt-10 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center text-sm font-bold"><div className="border border-border p-5">Seller / Asset Owner</div><ArrowRight className="size-5 text-gold"/><div className="bg-navy p-5 text-primary-foreground">TEKMA → Qualified Buyer</div></div></div><img src={advisory} alt="International executives discussing an energy opportunity" loading="lazy" width={1600} height={912} className="h-full min-h-96 w-full object-cover"/></div></section>
 <section className="bg-navy text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionHeading eyebrow="Our foundations" title="Vision, mission and values" light/><div className="mt-12 grid gap-8 lg:grid-cols-2"><div><h3 className="text-xs font-bold uppercase tracking-[0.2em] text-gold">Vision</h3><p className="mt-3 text-xl leading-8">To be a one-stop, integrated, world-class brokerage partner of choice, providing products and services that create efficient and sustainable value.</p></div><div><h3 className="text-xs font-bold uppercase tracking-[0.2em] text-gold">Mission</h3><p className="mt-3 text-xl leading-8">To build a globally respected brokerage company that understands and exceeds client expectations through excellent products, professional services and responsible business practices.</p></div></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Passion","Innovative solutions and superior service."],["Integrity","Commitment, professionalism and transparency."],["Ingenuity","Skilled, inventive and resourceful thinking."],["High performance","A constant drive to exceed expectations."]].map(([a,b],i)=><div key={a} className="border-t-2 border-gold bg-primary-foreground/5 p-6"><span className="text-xs text-primary-foreground/45">0{i+1}</span><h3 className="mt-8 text-xl font-bold">{a}</h3><p className="mt-3 text-sm leading-7 text-primary-foreground/65">{b}</p></div>)}</div></div></section>
 <section><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-28"><div className="aspect-[4/5] bg-gradient-to-br from-petroleum to-navy p-8 text-primary-foreground"><div className="flex h-full items-end border border-primary-foreground/25 p-6"><p className="text-sm text-primary-foreground/70">Professional portrait to be provided</p></div></div><div className="self-center"><SectionHeading eyebrow="Leadership" title="Experience at the highest level"/><p className="mt-8 text-xs font-bold uppercase tracking-[0.18em] text-petroleum">Chairman</p><h3 className="mt-2 text-3xl font-extrabold text-navy">Dr. Edmund Olu Ayoola</h3><p className="mt-5 leading-8 text-muted-foreground">A distinguished geologist and former Group Executive Director, Exploration and Production, of the Nigerian National Petroleum Corporation, where he held responsibility for major upstream oil and gas activities and subsidiaries.</p><Button asChild variant="link" className="mt-5 px-0 text-petroleum"><Link to="/leadership">Meet our chairman <ArrowRight/></Link></Button></div></div></section><CTASection/>
 </>}