import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, Globe2 } from "lucide-react";
import type { ReactNode } from "react";
import { Button } from "@/components/ui/button";

export function SectionHeading({ eyebrow, title, copy, light=false }: {eyebrow:string; title:string; copy?:string; light?:boolean}) {
  return <div className="max-w-3xl"><p className={`mb-4 text-xs font-extrabold uppercase tracking-[0.22em] ${light?'text-gold':'text-petroleum'}`}>{eyebrow}</p><h2 className={`text-3xl font-extrabold leading-tight sm:text-4xl lg:text-5xl ${light?'text-primary-foreground':'text-navy'}`}>{title}</h2>{copy&&<p className={`mt-5 max-w-2xl text-base leading-8 ${light?'text-primary-foreground/70':'text-muted-foreground'}`}>{copy}</p>}</div>
}

export function PageHero({ eyebrow, title, copy, image }: {eyebrow:string; title:string; copy:string; image:string}) {
 return <section className="relative min-h-[620px] overflow-hidden bg-navy text-primary-foreground"><img src={image} alt="" width={1600} height={900} className="absolute inset-0 size-full object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/80 to-transparent"/><div className="relative mx-auto flex min-h-[620px] max-w-7xl items-end px-5 pb-20 pt-28 lg:px-8"><div className="max-w-4xl"><p className="mb-5 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.22em] text-gold"><span className="h-px w-10 bg-gold"/>{eyebrow}</p><h1 className="max-w-4xl text-4xl font-extrabold uppercase leading-[1.06] sm:text-5xl lg:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-primary-foreground/80 sm:text-lg">{copy}</p></div></div></section>
}

export function CTASection(){return <section className="bg-petroleum text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 md:grid-cols-[1fr_auto] md:items-end lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold">Start a conversation</p><h2 className="mt-3 max-w-3xl text-3xl font-extrabold uppercase sm:text-4xl">Have an asset or opportunity to discuss?</h2><p className="mt-4 max-w-2xl text-primary-foreground/75">We welcome enquiries from genuine buyers, sellers, asset owners and duly authorised mandate holders.</p></div><div className="flex flex-wrap gap-3"><Button asChild size="lg" className="min-h-12 rounded-none bg-gold text-navy hover:bg-primary-foreground"><Link to="/opportunities">Submit an opportunity <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline" className="min-h-12 rounded-none border-primary-foreground/40 bg-transparent text-primary-foreground hover:bg-primary-foreground hover:text-navy"><Link to="/contact">Speak with Tekma</Link></Button></div></div></section>}

export function GlobalMap(){ return <div className="relative min-h-[430px] overflow-hidden border border-primary-foreground/15 bg-primary-foreground/5 p-6"><Globe2 className="absolute left-1/2 top-1/2 size-[360px] -translate-x-1/2 -translate-y-1/2 text-primary-foreground/10 gentle-drift"/><svg viewBox="0 0 800 380" className="absolute inset-0 size-full" aria-hidden="true"><path d="M80 220 Q300 20 720 140" fill="none" stroke="var(--color-ocean)" strokeWidth="2" className="orbital-dash"/><path d="M130 100 Q420 370 700 80" fill="none" stroke="var(--color-gold)" strokeWidth="2" className="orbital-dash"/><path d="M100 310 Q410 80 730 280" fill="none" stroke="var(--color-energy)" strokeWidth="2" className="orbital-dash"/>{[[100,220,"Africa"],[270,96,"Europe"],[430,205,"Middle East"],[650,115,"Asia"],[680,290,"North America"]].map(([x,y,n],i)=><g key={String(n)}><circle cx={Number(x)} cy={Number(y)} r="7" fill={["var(--color-energy)","var(--color-gold)","var(--color-magenta)","var(--color-ocean)","var(--color-purple)"][i]}/><text x={Number(x)+13} y={Number(y)+5} fill="currentColor" fontSize="14">{n}</text></g>)}</svg><p className="absolute bottom-6 left-6 max-w-md text-xs leading-6 text-primary-foreground/60">Connection points illustrate market reach through business networks and do not represent physical offices.</p></div> }

export function BulletGrid({items}:{items:string[]}){return <div className="grid gap-3 sm:grid-cols-2">{items.map(x=><div key={x} className="flex items-center gap-3 border-b border-border py-4 font-semibold text-navy"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-energy/15 text-energy"><Check className="size-4"/></span>{x}</div>)}</div>}

export function LegalPage({title, intro, children}:{title:string;intro:string;children:ReactNode}){return <><section className="bg-navy px-5 py-24 text-primary-foreground lg:px-8"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold">TEKMA Global Partners Limited</p><h1 className="mt-4 text-4xl font-extrabold sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-primary-foreground/70">{intro}</p></div></section><article className="prose prose-slate mx-auto max-w-4xl px-5 py-16 [&_h2]:mt-10 [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:text-navy [&_p]:leading-8 [&_p]:text-muted-foreground">{children}</article></>}